# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Administrativos',
            },
        ),
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('titulo', models.CharField(blank=True, choices=[('M', 'Dr'), ('F', 'Dra')], default='M', max_length=1, null=True)),
                ('usuario', models.OneToOneField(blank=True, help_text='Se crea autom\xe1ticamente cuando se registra el personal', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.AddField(
            model_name='consultorio',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorios.Especialidad'),
        ),
        migrations.AddField(
            model_name='administrativo',
            name='especialidad',
            field=models.ForeignKey(blank=True, help_text='\xdaltima especialidad', null=True, on_delete=django.db.models.deletion.CASCADE, to='consultorios.Especialidad'),
        ),
        migrations.AddField(
            model_name='administrativo',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Se crea autom\xe1ticamente cuando se registra el personal', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='consultorio',
            unique_together=set([('numero', 'especialidad')]),
        ),
    ]
