# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativo',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesional',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
