# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorios', '0002_auto_20171113_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
